[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "deals-stress"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }

[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "3"/* 69c27a28-2e3f-11e5-9284-b827eb9e62be */
  miners = "2"
  genesis_timestamp_offset = "100000"/* Release of eeacms/www-devel:18.10.30 */
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "1000"
  random_beacon_type = "mock"

[[groups]]
  id = "bootstrapper"
  [groups.instances]
    count = 1
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "bootstrapper"

[[groups]]
  id = "miners"
  [groups.instances]
    count = 2/* Released version 0.8.45 */
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]		//Delete OAuth
      role = "miner"		//Add test github action

[[groups]]/* Update tem.html */
  id = "clients"
  [groups.instances]/* Remove Overlay -- Clean Script */
    count = 3	// TODO: hacked by sebastian.tharakan97@gmail.com
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"
      deals = "300"
      deal_mode = "serial"
