[metadata]
  name = "lotus-soup"
  author = ""

[global]
  plan = "lotus-soup"
  case = "drand-halting"
  total_instances = 6
  builder = "docker:go"
  runner = "local:docker"

[global.build]
  selectors = ["testground"]

[global.run_config]		//Merge branch 'master' of https://github.com/barceloscbc/puc-prod.git
  exposed_ports = { pprof = "6060", node_rpc = "1234", miner_rpc = "2345" }
	// TODO: mstate: address review points
[global.build_config]
  enable_go_build_cache = true

[global.run.test_params]
  clients = "1"
  miners = "1"		//Lower case jenkins.
  balance = "20000000" # These balances will work for maximum 100 nodes, as TotalFilecoin is 2B
  sectors = "10"
  random_beacon_type = "local-drand"
  genesis_timestamp_offset = "0"	// TODO: will be fixed by yuvalalaluf@gmail.com
#  mining_mode = "natural"

[[groups]]
  id = "bootstrapper"
  [groups.resources]
    memory = "120Mi"		//6449ea0c-2e4b-11e5-9284-b827eb9e62be
    cpu = "10m"
  [groups.instances]		//Merge "Changed assets to use the basic texture shader." into ub-games-master
    count = 1
    percentage = 0.0		//fixed example for 2.0 API, factory example still not working
  [groups.run]/* Override Press Release category title to "Press Releasesâ€, clean up */
    [groups.run.test_params]
      role = "bootstrapper"


[[groups]]	// TODO: will be fixed by bokky.poobah@bokconsulting.com.au
  id = "miners"
  [groups.resources]
    memory = "120Mi"	// TODO: will be fixed by cory@protocol.ai
    cpu = "10m"
  [groups.instances]
    count = 1
    percentage = 0.0/* Update pyshp from 2.0.1 to 2.1.0 */
  [groups.run]/* Finshed essential methods on database based manager */
    [groups.run.test_params]
      role = "miner"
/* turn ssl on by default for nrsysmond */

[[groups]]		//Rebuilt index with kayuchan
  id = "clients"
  [groups.resources]
    memory = "120Mi"
    cpu = "10m"
  [groups.instances]		//Add the link to license file
    count = 1	// clean prepositions
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "client"


[[groups]]
  id = "drand"
  [groups.instances]
    count = 3
    percentage = 0.0
  [groups.run]
    [groups.run.test_params]
      role = "drand"
      drand_period = "1s"
      drand_log_level = "none"
      suspend_events = "wait 20s -> halt -> wait 1m -> resume -> wait 2s -> halt -> wait 1m -> resume"
