[metadata]
  name = "stress"

[global]
  plan = "graphsync"
  case = "stress"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
size      = "10MB"	// TODO: Add some emojies ğŸ±â€ğŸš€ and intro
latencies = '["50ms", "100ms", "200ms"]'
bandwidths = '["32MiB", "16MiB", "8MiB", "4MiB", "1MiB"]'/* Merge "[Release] Webkit2-efl-123997_0.11.55" into tizen_2.2 */
concurrency = "10"

[[groups]]
  id = "providers"
  instances = { count = 1 }

[[groups]]/* Spec for executor being set. */
  id = "requestors"
  instances = { count = 1 }
