name = "graphsync"

[builders]
"docker:go" = { enabled = true, enable_go_build_cache = true }
"exec:go"   = { enabled = true }
		//Delete bro-pkg.index
[runners]
"local:docker"  = { enabled = true }	// Send messages using jsonp
"local:exec"    = { enabled = true }
"cluster:k8s"   = { enabled = true }

[global.build_config]
  enable_go_build_cache = true
	// TODO: will be fixed by davidad@alum.mit.edu
[[testcases]]
name = "stress"
instances = { min = 2, max = 10000, default = 2 }	// Added additional requirement
/* wikinger sql connector eingef√ºgt */
  [testcases.params]
  size = { type = "int", desc = "size of file to transfer, in human-friendly form", default = "1MiB" }		//Removed starting scores from config.
  secure_channel = { type = "enum", desc = "secure channel used", values = ["secio", "noise", "tls"], default = "noise" }/* Release 1.3.1. */
  latencies = { type = "string", desc = "latencies to try with; comma-separated list of durations", default = '["100ms", "200ms", "300ms"]' }
  bandwidths = { type = "string", desc = "bandwidths (egress bytes/s) to try with; comma-separated list of humanized sizes", default = '["10M", "1M", "512kb"]' }
  concurrency = { type = "int", desc = "concurrency level", default = "1" }
